app_Gossip_Project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'home#home_page', as:'home_page'
  get '/team', to:'home#about_us', as: 'about_us'
  get '/contact', to:'home#contact_us', as: 'contact_us'
  get '/welcome/:name', to:'home#welcome', as:'welcome'
  get '/user/info/:id', to:'user#user_info', as:'user_info'
  get '/gossip/show/:id', to:'gossip#show_gossip', as:'gossip_info'
  
end

app_Gossip_Project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app_Gossip_Project/app/models/city.rb
class City < ApplicationRecord
end

app_Gossip_Project/app/models/comment.rb
class Comment < ApplicationRecord
end

app_Gossip_Project/app/models/gosssip.rb
class Gosssip < ApplicationRecord
    belongs_to :user
end

app_Gossip_Project/app/models/like.rb
class Like < ApplicationRecord
end

app_Gossip_Project/app/models/message_user.rb
class MessageUser < ApplicationRecord
    belongs_to :private_message 
    belongs_to :user
end

app_Gossip_Project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :user
end

app_Gossip_Project/app/models/tag.rb
class Tag < ApplicationRecord
end

app_Gossip_Project/app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :tag 
    belongs_to :gosssip
end

app_Gossip_Project/app/models/user.rb
class User < ApplicationRecord 
    belongs_to :city
end

app_Gossip_Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    
    
    
end

app_Gossip_Project/app/controllers/gossip_controller.rb
class GossipController < ApplicationController 
    def show_gossip 
        @gossip=Gosssip.find(params["id"])
    end
end

app_Gossip_Project/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home_page
        @gossips=Gosssip.all 
        users=User.all 
        userLength=users.length 
        randNum=rand(0..userLength)
        @name=users[randNum].first_name
    end 

    def about_us 

    end 

    def contact_us 
        users=User.all 
        getRandom=rand(0..users.length)
        @user=users[getRandom]
    end 

    def welcome 
        @name=params['name']
        
    end 

    def show_gossip 
        
    end

end

app_Gossip_Project/app/controllers/user_controller.rb
class UserController < ApplicationController 
    def user_info
        @user=User.find(params["id"])
    end
end

app_Gossip_Project/app/helpers/application_helper.rb
module ApplicationHelper
end

app_Gossip_Project/app/helpers/gossip_helper.rb
module GossipHelper
end

app_Gossip_Project/app/helpers/home_helper.rb
module HomeHelper
end

app_Gossip_Project/app/helpers/user_helper.rb
module UserHelper
end

app_Gossip_Project/app/views/gossip/show_gossip.erb
<br/>

<h2> Get Gossip Info </h2>
<div> Ecrit Par: <%=@gossip.user.first_name %>
<div> Titre <%= @gossip.title %> </div> 
<div> Contenu <%= @gossip.content %> </div>

app_Gossip_Project/app/views/home/about_us.erb
<br/>
<div> Ceci Est La Page qui presente les infos sur notre equipe </div> 
<p> Bonjour je m'apelle Reuben Chouraki et vu que je suis un loser et aussi que je sais deja coder, cest moi qui est cree cette page tout seul! et donc je n'ai pas d'equipe j'espere que je ne vais pas perdre un joker a cause de cela </p>

app_Gossip_Project/app/views/home/contact_us.erb
<br/> 

<h2> Ville: <%=@user.city.name%> Code Postale: <%=@user.city.zip_code %> </h2>

app_Gossip_Project/app/views/home/home_page.erb
<h1 class="text-center"> Mes Patins </h1> 
<div class="text-center"> <%= link_to 'Welcome Page ', welcome_path(@name) %> </div>
<% @gossips.length.times do |i| %> 
  <div class="card">
    <div class="text-center"> Ecrit par <%=@gossips[i].user.first_name %>  <%=@gossips[i].user.last_name %> </div>

    <div class="text-center"> Titre: <%= @gossips[i].title %> </div> 
    
    <div class="text-center"> Contenu: <%=@gossips[i].content %> </div>  

    <div class="text-center"> <%= link_to 'Infos Du User ', user_info_path(@gossips[i].user.id) %> </div> 

    <div class="text-center"> <%= link_to 'Page du Gossip', gossip_info_path(@gossips[i].id) %> </div>
    </div>

    <br/>
    <br/>

<% end %> 



    

app_Gossip_Project/app/views/home/welcome.erb
<br/>

<h1> Welcome To The Application <%=@name %> </h1>

app_Gossip_Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header> <h1> Ceci Est Mon Header qui va se trouver sur toutes mes pages sur cette application </h1> 
  <div> <%= link_to 'Home Page ', home_page_path %> </div>
    <div> <%= link_to 'Notre Equipe ', about_us_path %> </div>
    <div> <%= link_to 'Contact ', contact_us_path %> </div>
    
  </header>
    <%= yield %> 
   
  </body>
</html>

app_Gossip_Project/app/views/user/user_info.erb
<br/>

<h2> Infos Sur Le User </h2>
<div> Num email: <%= @user.email %> </div>
<div> Prenom et Nom:  <%=@user.first_name%> <%= @user.last_name %> </div>
<div> Description: <%=@user.description %> </div>